language: perl
perl:
  - "5.18.1_thr"
env:
  - EXTENDED_TESTING=1
matrix:
  include:
    - perl: "5.8.1"
      install:
        - "cpanm -n Exporter Class::ISA"
        - "cpanm -n Test::Requires Test::Fatal Test::LeakTrace"
        - "cpanm Exporter::Tiny"
        - "cpanm -n indirect multidimensional bareword::filehandles"
        - "cpanm -n Moo"
    - perl: "5.6.2"
      install:
        - "perl -Idevel.travis -MCPAN -e'install q/Scalar::Util/'"
        - "perl -Idevel.travis -MCPAN -e'install q/Text::Balanced/'"
        - "perl -Idevel.travis -MCPAN -e'install q/Exporter/'"
        - "perl -Idevel.travis -MCPAN -e'install q/Class::ISA/'"
        - "perl -Idevel.travis -MCPAN -e'install q/Exporter::Tiny/'"
before_install:
  - "source devel.travis/travis-perlbrew"
  - "perlbrew install-cpanm -f"
  - "perl -V"
install:
  - "cpanm -n Test::Requires Test::Fatal Test::LeakTrace"
  - "cpanm Exporter::Tiny"
  - "cpanm -n indirect multidimensional bareword::filehandles"
  - "cpanm -n Moose MooseX::Types::Common"
  - "cpanm -n Mouse MouseX::Types"
  - "cpanm -n Moo"
  - "cpanm -n Class::InsideOut"
script:
  - "HARNESS_IS_VERBOSE=1 prove -Ilib t"
